version: '3'

services:
  app:
    container_name: go-driver-api
    build:
      context: ./
      dockerfile: .setup/build/dev/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - go-driver-api
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-driver
      MYSQL_PASSWORD: root
      TZ: "America/Sao_Paulo"
    volumes:
      - .docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - go-driver-api

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - go-driver-api

networks:
  go-driver-api:
    driver: bridge