version: '3'

services:
  app:
    container_name: go-driver
    build:
      context: ./
      dockerfile: .setup/build/dev/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - go-driver
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-driver
      MYSQL_PASSWORD: root
    volumes:
      - .docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - go-driver

networks:
  go-driver:
    driver: bridge