### Criar novo usuário
POST {{base_url}}/users
Content-Type: application/json

{
  "name": "Paulo Braga Antunes",
  "email": "paulosantunes@gmail.com",
  "password": "12121321"
}

### Listar usuário por Id
GET {{base_url}}/users/4
Accept: application/json

### Atualizar usuário
PUT {{base_url}}/users/8
Accept: application/json

{
  "name": "Paulo Braga",
  "email": "pauloss@gmail.com",
  "password": "1245sda"
}

### Deletar usuário
DELETE {{base_url}}/users/8

